version: "3.9"
services:
  backend:
    build: .
    ports:
      - "${backendPort}:8000"
    environment:
      - BACKEND_URL=${backendUrl}
  nginx:
    build: ./nginx
    ports:
      - "${frontEndPort}:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${backendUrl}
      - FRONTEND_URL=${frontendUrl}