version: "3.9"
services:
  backend:
    env_file:
      - .env
    build: ./server
    ports:
      - "${backendPort}:8000"
    environment:
      - BACKEND_URL=${backendUrl}
  nginx:
    env_file:
      - .env
    build: ./client
    ports:
      - "${frontEndPort}:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=${backendUrl}
      - FRONTEND_URL=${frontendUrl}