# Generated by Django 4.2 on 2023-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='sentement',
            field=models.FloatField(default=0.0),
        ),
    ]
