# Generated by Django 4.2 on 2023-04-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0002_news_sentement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(max_length=256),
        ),
    ]
