# Generated by Django 4.2 on 2023-04-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0004_alter_news_author_alter_news_source_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
