# Generated by Django 4.2 on 2023-04-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0005_alter_news_source_id_alter_news_source_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
