# Generated by Django 4.2 on 2023-04-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0007_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='author',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_id',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
