# Generated by Django 4.2 on 2023-04-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0008_alter_news_author_alter_news_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='list_of_keywords',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
