# Generated by Django 4.2 on 2023-05-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_module', '0009_news_list_of_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
    ]
