# Generated by Django 4.2 on 2023-04-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0003_user_profile_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='User',
        ),
    ]
